### ISSUE TITLE
EmmetInstall error for Emmet Vim

### ISSUE THREAD

**Issue by daedelus-j** [square/maximum-awesome#133]
Not entirely sure if this is necessarily an MA issue but i had this plugin working before MA install... 

added to ~/.bundle.local:

Bundle 'mattn/emmet-vim'

added to .vimrc.local;

let g:user_emmet_install_global = 0
autocmd FileType tmpl,html,css EmmetInstall
let g:user_emmet_leader_key='\e'

open an html file and receive these errors:
Error detected while processing FileType Auto commands for "html":
E492: Not an editor command: EmmetInstall 

Didn't see any references for installing bundles, you're just supposed to paste github repos there, right? Perhaps a bundle add section in Readme would help. Will fork and pull request once I understand how it works :)

**Comment by rudle** [comment]
I'm going to close this issue as it's been open for more than a year. Please re-open if it's still valid.
