### ISSUE TITLE
E492: Not an editor command: NERDTree

### ISSUE THREAD

**Issue by kennedy-han** [square/maximum-awesome#160]
when i open vim, and press ,d
it told me 
E492: Not an editor command: NERDTree

**Comment by jinfagang** [comment]
I already run `BundleInstall!`， but after that open vim again, still says: `Not an editor command: NERDTree`

**Comment by binkabir** [comment]
I used this process to get it working. 
1. edited the `~/.vimrc file` 
2. add this `Plugin https://github.com/scrooloose/nerdtree.git`
3. saved and update the bundle is `BundleInstall`
