### ISSUE TITLE
Ignore swap files

### ISSUE THREAD

**Issue by kristoferjoseph** [square/maximum-awesome#170]
Do you actually rely on .swp files?
I find that these are a legacy hurdle that don't offer much benefit but do cause a lot of annoyance.
?
```
set nobackup
set noswapfile
set wildignore=*.swp,*.bak
```

**Comment by jontonsoup** [comment]
+1 for this

**Comment by rudle** [comment]
> There is absolutely no reason to have .swp files anymore.

I disagree. swp files do have a purpose and I don't think it's right to disable them by default. If you're annoyed by them :hankey: ing on your machine, I suggest you set the suggested options in your ~/.vimrc.local.
