### ISSUE TITLE
rake   install fail!

### ISSUE THREAD

**Issue by zengxianbing** [square/maximum-awesome#178]
-- Homebrew --------------------------------------------------------------------
which: no brew in (/usr/local/rvm/gems/ruby-2.0.0-p481/bin:/usr/local/rvm/gems/ruby-2.0.0-p481@global/bin:/usr/local/rvm/rubies/ruby-2.0.0-p481/bin:/usr/lib/qt-3.3/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/rvm/bin:/usr/local/go/bin:/root/bin)
See Linuxbrew: http://brew.sh/linuxbrew/
rake aborted!
Homebrew must be installed before continuing.
/root/桌面/github/vim/maximum-awesome/Rakefile:123:in `block (2 levels) in <top (required)>'
/root/桌面/github/vim/maximum-awesome/Rakefile:229:in`block in <top (required)>'
Tasks: TOP => install:brew
(See full trace by running task with --trace)

**Comment by sarmstr5** [comment]
I ran into issues with installing on ubuntu 17.04, is this still the recommended way of installation?

**Comment by rudle** [comment]
Linux remains unsupported. See Issue #31 for workarounds.
