### ISSUE TITLE
Move project to Neobundle

### ISSUE THREAD

**Issue by morenoh149** [square/maximum-awesome#184]
MA is currently using and out of date version of vundle.
The author has made a new version and renamed it [neobundle](https://github.com/Shougo/neobundle.vim)

**Comment by rudle** [comment]
Thanks for the tip! However, it seems that neobundle is not yet stable, quoting from the README:

> Note: Neobundle is not a stable plugin manager. If you want a stable plugin manager, you should use Vundle plugin. It well works widely and it is more tested. If you want to use extended features, you can use neobundle.

I'll star the project and keep an eye on its becoming stable.
