### ISSUE TITLE
Bug: Mouse highlighting on third vertical panel

### ISSUE THREAD

**Issue by Sonblind** [square/maximum-awesome#197]
#### When highlighting over the third vertical window pane (far right) the left most pane is the one highlighted. 

Currently only the two left windows can be selected or scrolled:

![screen shot 2015-06-05 at 1 30 50 pm](https://cloud.githubusercontent.com/assets/2101499/8011545/7e4495d8-0b87-11e5-9149-9824ecad507f.png)

**Comment by rudle** [comment]
huh, that's a weird bug! I don't think it's specific to maximum-awesome though. I was able to reproduce the error with a minimal .vimrc just: `set mouse=a`.

If you're so inclined, you might submit a bug upstream to https://code.google.com/p/vim/
