### ISSUE TITLE
Failed to download resource "libevent"

### ISSUE THREAD

**Issue by yyjw** [square/maximum-awesome#215]
brew install tmux
==> Installing tmux dependency: libevent
==> Downloading https://downloads.sourceforge.net/project/levent/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "libevent"
Download failed: https://downloads.sourceforge.net/project/levent/libevent/libevent-2.0/libevent-2.0.22-stable.tar.gz
rake aborted!
Command failed with status (1): [brew install tmux ...]
/Users/user/maximum-awesome/Rakefile:9:in `brew_install'
/Users/user/maximum-awesome/Rakefile:170:in `block (2 levels) in <top (required)>'
/Users/user/maximum-awesome/Rakefile:237:in `block in <top (required)>'
Tasks: TOP => install:tmux

**Comment by yashiro1899** [comment]
https://github.com/Homebrew/homebrew/pull/47372

**Comment by rudle** [comment]
@yyjw this looks like an upstream issue. I think that `brew update && rake` will work. Please reopen this issue if there are more problems.
