### ISSUE TITLE
unknown option: mouse-utf8

### ISSUE THREAD

**Issue by huanzhang** [square/maximum-awesome#216]
I got the error as $subject.

PS: I was on OS X EI Capitan.

![tmux-mouse-utf8-not-found](https://cloud.githubusercontent.com/assets/3303276/13131073/159968d4-d624-11e5-9d0a-93e4547048b6.png)

**Comment by JHKennedy4** [comment]
What version of tmux? You may need to upgrade. I believe the current config targets tmux 2.1.

**Comment by huanzhang** [comment]
![tmux-mouse-utf8-not-found](https://cloud.githubusercontent.com/assets/3303276/13131007/c79309b0-d623-11e5-9cd3-a1666adeaa4e.png)

![screen shot 2016-02-18 at 09 42 12](https://cloud.githubusercontent.com/assets/3303276/13131040/e9d15504-d623-11e5-87ae-2e633bfc53bc.png)

My tmux is the latest version - 2.2

**Comment by rudle** [comment]
@huanzhang it's not clear how you have 2.2 installed. I can't find it in homebrew after a `brew update` and even the tmux homepage shows 2.1 as latest[1].

I would suggest installing tmux 2.1 as that's the version we have tested.

[1] https://tmux.github.io/

**Comment by huanzhang** [comment]
@rudle my tmux is the HEAD version

```
➜  ~ brew list --versions | grep tmux
tmux HEAD
```

**Comment by rudle** [comment]
Thank you. It would appear as though this version of tmux is not yet supported. Please use tmux 2.1 as it is the latest released version, per https://raw.githubusercontent.com/tmux/tmux/master/CHANGES
