### ISSUE TITLE
Hitting ⌘-R hides everything

### ISSUE THREAD

**Issue by JHKennedy4** [square/maximum-awesome#217]
When I hit ⌘-R prematurely when switching to the browser, it looks like the entire console output is scrolled out of view somehow. I have to try and interact with each tmux pane to make them render again, and I can't get my vim buffers to reappear most of the time.

This happens a few dozen times a day as I switch between browser and terminal, and it gets a bit frustrating to have to close vim or even quit out of tmux to get back to where I was.

Does anyone know why this happens and what can be done to address it?

**Comment by rudle** [comment]
Hi there, I see the same issue as you.

I looked at the tmux bindings (`C-a ?`) and didn't see any specific bindings mapped to ⌘-r, so I don't think this is something we can disable in config.

When this happens to me, I usually type `reset` in my terminal and things get back to normal. From vim, you I background the process (`C-z`) then `reset` and finally `fg` the process again. Another workaround I've seen is to `:tabnew` within vim and then close it `:tabcl`.

Hope this helps, please re-open the issue if you think we can fix this issue once and for all.

**Comment by JHKennedy4** [comment]
Thanks so much. I'll definitely keep digging. One other technique I found
was going to tmux's window listing and reselecting. I think that's (C-a w).
