### ISSUE TITLE
how to support c++ 11 syntax error?

### ISSUE THREAD

**Issue by fredericky** [square/maximum-awesome#219]
there're still syntax errors when using c++ 11. For example, vector<int> v{1,2}. Can you please help to solve this problem? Thanks!

**Comment by rudle** [comment]
@fredericky It sounds like you're trying to configure the syntastic plugin that comes with maximum-awesome. More information on that can be found here: https://github.com/scrooloose/syntastic

Please reopen this issue if you find an issue related to maximum-awesome
