### ISSUE TITLE
Installation not working out of the box

### ISSUE THREAD

**Issue by cassidoo** [square/maximum-awesome#221]
Setting up a new computer, and when I hit `rake` everything looks good, but when I open vim, nothing was actually installed.  I tried restarting iTerm and it didn't help.  Solarized works when I add that as the colorscheme, but that's it.  Plus, my .vimrc is empty.  What could be the problem?

**Comment by rudle** [comment]
That's surprising. Out of the box support is important to us.

Some questions:

1) Is this really a new computer? Was there an extant .vimrc in place before you executed `rake`? I'm guessing not, but I figured I'd check anyway.

2) Can you attach the output of the initial `rake` if you still have it available? If not, can you execute it again and attach the output?

**Comment by cassidoo** [comment]
1) Yes, really new computer, no .vimrc in place.

2) I executed it again and got:
```
-- Homebrew ---------------------------------------------------------------
Done!

-- Homebrew Cask ---------------------------------------------------------------

-- the_silver_searcher ---------------------------------------------------------

-- iterm2 ----------------------------------------------------------------------

-- ctags -----------------------------------------------------------------------

-- reattach-to-user-namespace --------------------------------------------------

-- tmux ------------------------------------------------------------------------

-- MacVim ----------------------------------------------------------------------
Please add ~/bin to your PATH, e.g. run this command:

 echo 'export PATH="~/bin:$PATH"' >> ~/.bashrc

The exact command and file will vary by your shell and configuration.

-- symlink ---------------------------------------------------------------------

-- vundle ----------------------------------------------------------------------
~/bin/vim -c "PluginInstall!" -c "q" -c "q"

-- iterm2 colorschemes ---------------------------------------------------------

-- iterm2 profiles -------------------------------------------------------------

 Your turn!

 Go and manually set up Solarized Light and Dark profiles in iTerm2.
 (You can do this in 'Preferences' -> 'Profiles' by adding a new profile,
 then clicking the 'Colors' tab, 'Load Presets...' and choosing a Solarized option.)
 Also be sure to set Terminal Type to 'xterm-256color' in the 'Terminal' tab.

 Enjoy!```

**Comment by rudle** [comment]
Can you show me the output of `ls -l ~/.vim*`?

If you're feeling adventurous and know ruby, you might also try invoking some of the Rakefile manually in a console. I'm thinking in particular about the part where the Rakefile explicitly links maximum-awesome's `vimrc` to `~/.vimrc`.

**Comment by cassidoo** [comment]
```lrwxr-xr-x  1 ...  staff    38 May 17 13:41 /Users/.../.vim -> /Users/.../maximum-awesome/vim
lrwxr-xr-x  1 ...  staff    48 May 17 12:38 /Users/.../.vim.bak -> /Users/.../Documents/maximum-awesome/vim
-rw-------  1 ...  staff  3237 May 17 15:50 /Users/.../.viminfo
lrwxr-xr-x  1 ...  staff    40 May 17 13:41 /Users/.../.vimrc -> /Users/.../maximum-awesome/vimrc
lrwxr-xr-x  1 ...  staff    50 May 17 12:38 /Users/.../.vimrc.bak -> /Users/.../Documents/maximum-awesome/vimrc
lrwxr-xr-x  1 ...  staff    48 May 17 13:41 /Users/.../.vimrc.bundles -> /Users/.../maximum-awesome/vimrc.bundles
lrwxr-xr-x  1 ...  staff    58 May 17 13:41 /Users/.../.vimrc.bundles.bak -> /Users/.../Documents/maximum-awesome/vimrc.bundles
-rw-r--r--  1 ...  staff     0 May 17 13:41 /Users/.../.vimrc.bundles.local
-rw-r--r--  1 ...  staff   999 May 17 13:41 /Users/.../.vimrc.local```

**Comment by rudle** [comment]
Based on what you've shown there, `.vimrc` and its friends are present in the place where `vim` expects it to be.

Can you restate the issue you're having? I'm afraid I've lost the thread.

**Comment by cassidoo** [comment]
Not sure what happened, but I restarted the computer and now it works.  Thanks everyone, and sorry for the confusion!  Maybe it was just something funky with the machine.

**Comment by eventualbuddha** [comment]
My guess is that `~/bin` wasn't in your `PATH` so it wasn't using the vim that maximum-awesome installs. Can you remember whether you ran `echo 'export PATH="~/bin:$PATH"' >> ~/.bashrc` and, if so, whether you opened a new shell after that?

**Comment by cassidoo** [comment]
Ooh we did do that command, but I could totally see that being the problem (not opening a new shell/not sourcing the bashrc after exporting the path).  Good call!!
