### ISSUE TITLE
Error when installing 

### ISSUE THREAD

**Issue by dchaid** [square/maximum-awesome#228]
retina:maximum-awesome davidchaid$ git clone https://github.com/square/maximum-awesome.git && cd maximum-awesome && rake --trace
Cloning into 'maximum-awesome'...
remote: Counting objects: 817, done.
remote: Total 817 (delta 0), reused 0 (delta 0), pack-reused 817
Receiving objects: 100% (817/817), 386.34 KiB | 0 bytes/s, done.
Resolving deltas: 100% (364/364), done.
Checking connectivity... done.
** Invoke default (first_time)
** Invoke install (first_time)
** Execute install
** Invoke install:brew (first_time)
** Execute install:brew

-- Homebrew --------------------------------------------------------------------
** Invoke install:brew_cask (first_time)
** Execute install:brew_cask

-- Homebrew Cask ---------------------------------------------------------------
brew install brew-cask 
Error: No available formula with the name "brew-cask" 
==> Searching for similarly named formulae...
This similarly named formula was found:
homebrew/completions/brew-cask-completion ✔
To install it, run:
  brew install homebrew/completions/brew-cask-completion ✔
==> Searching taps...
Error: No formulae found in taps.
rake aborted!
Command failed with status (1): [brew install brew-cask ...]
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/davidchaid/maximum-awesome/maximum-awesome/maximum-awesome/Rakefile:9:in `brew_install'
/Users/davidchaid/maximum-awesome/maximum-awesome/maximum-awesome/Rakefile:137:in `block (2 levels) in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/davidchaid/maximum-awesome/maximum-awesome/maximum-awesome/Rakefile:233:in `block in <top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/local/Cellar/ruby/2.3.1_2/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
Tasks: TOP => install:brew_cask

**Comment by willfaught** [comment]
This has been broken for months. Sadly, this repo seems to be abandoned. I switched to Janus, seems good.

**Comment by dchaid** [comment]
Thanks!

**Comment by cassidoo** [comment]
You can manually fix your Rakefile and do what #224 does, too, if you want to stick with this repo!
