### ISSUE TITLE
Error: caskroom/cask was moved. Tap homebrew/cask-cask instead.

### ISSUE THREAD

**Issue by dongrerohan421** [square/maximum-awesome#258]
while running rake command I am getting Error: caskroom/cask was moved. Tap homebrew/cask-cask instead.

**Comment by jmaygarden** [comment]
As a workaround, I changed line 134 of Rakefile as follows:

`diff --git a/Rakefile b/Rakefile
index cf68178..b019b3a 100644
--- a/Rakefile
+++ b/Rakefile
@@ -131,7 +131,7 @@ namespace :install do
   task :brew_cask do
     step 'Homebrew Cask'
     system('brew untap phinze/cask') if system('brew tap | grep phinze/cask > /dev/null')
-    unless system('brew tap | grep caskroom/cask > /dev/null') || system('brew tap caskroom/cask')
+    unless system('brew tap | grep homebrew/cask > /dev/null') || system('brew tap caskroom/cask')
       abort "Failed to tap caskroom/cask in Homebrew."
     end`
